# Generated by Django 5.1.1 on 2024-09-25 14:31

import core.models.movie
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField()),
                ('original_language', models.CharField(max_length=6)),
                ('original_title', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('overview', models.TextField()),
                ('release_date', models.DateField(null=True)),
                ('popularity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('vote_average', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('vote_count', models.IntegerField(default=0)),
                ('backdrop_path', models.FileField(default=None, null=True, upload_to=core.models.movie.movie_file_directory)),
                ('poster_path', models.FileField(default=None, null=True, upload_to=core.models.movie.movie_file_directory)),
                ('genres', models.ManyToManyField(db_table='movie_genre', to='core.genre')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
